name: fedora-rice
description: My riced Hyprland Nvidia build

base-image: ghcr.io/wayblueorg/hyprland
image-version: latest

modules:
  - type: rpm-ostree
    install:
      - nwg-look
      - rofi-wayland
      - swww
      - dunst
      - playerctl
      - brightnessctl
      - papirus-icon-theme
      - kitty

  - type: files
    files:
      - source: system
        destination: /
